{{- if .Values.serviceMonitor.enabled -}}
{{- if .Capabilities.APIVersions.Has "operator.victoriametrics.com/v1beta1/VMServiceScrape" }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "vault-secrets-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
{{- if .Values.serviceMonitor.labels }}
  {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
{{- end }}
spec:
  endpoints:
    - port: http-metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: "/metrics"
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelConfigs:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
  jobLabel: "vault-secrets-operator"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vault-secrets-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- else }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vault-secrets-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
{{- if .Values.serviceMonitor.labels }}
  {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
{{- end }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      port: http-metrics
      path: "/metrics"
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
  jobLabel: "vault-secrets-operator"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vault-secrets-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
{{- end }}