{{- if .Values.kubeApiServer.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ printf "%s-%s" (include "vm-operator.fullname" $) "apiserver" | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "vm-operator.labels" . | nindent 4 }}
spec: {{ .Values.kubeApiServer.spec | toYaml | nindent 2 }}
{{- end }}
