
{{- if .Values.coreDns.enabled }}
{{- if .Values.coreDns.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "vm-operator.fullname" $) "coredns" | trunc 63 | trimSuffix "-" }}
  namespace: kube-system
  labels:
    app: {{ include "vm-operator.fullname" . }}-coredns
    jobLabel: coredns
{{ include "vm-operator.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.coreDns.service.port }}
      protocol: TCP
      targetPort: {{ .Values.coreDns.service.targetPort }}
  selector:
    {{- with .Values.coreDns.service.selector -}}
    {{ toYaml . | nindent 4 }}
    {{- end}}
{{- end }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ printf "%s-%s" (include "vm-operator.fullname" $) "coredns" | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "vm-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: 'true'
      kubernetes.io/name: CoreDNS
  namespaceSelector:
    matchNames:
      - "kube-system"
{{ omit .Values.coreDns.spec "selector" "namespaceSelector" | toYaml | indent 2 }}
{{- end }}
