affinity: {}
caCerts:
  enabled: false
  secrets: []
dexK8sAuthenticator:
  clusters:
  - client_id: my-cluster
    client_secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
    description: Example Cluster Long Description...
    issuer: https://dex.example.com
    k8s_ca_uri: https://url-to-your-ca.crt
    k8s_master_uri: https://my-cluster.example.com
    name: my-cluster
    redirect_uri: https://login.example.com/callback/my-cluster
    short_description: My Cluster
  debug: false
  port: 5555
  web_path_prefix: /
global:
  deployEnv: dev
image:
  pullPolicy: Always
  repository: mintel/dex-k8s-authenticator
  tag: 1.4.0
imagePullSecrets: {}
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: []
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  annotations: {}
  port: 5555
  type: ClusterIP
tolerations: []
