
# Set the address for vault (by default we assume you are running a dev
# instance of vault in the same namespace as the operator) and specify the
# authentication method for the operator.  Possible values are 'token',
# 'kubernetes', or 'approle'.

# If the authentication method is 'kubernetes' the Helm chart
# ensures that the Service Account included the needed rights. The default path
# for the Kubernets Auth method is 'auth/kubernetes', if you enabled it under
# another path you must change the 'kubernetesPath' value. You must also
# provide the role which should be used for the authentication.

vault:
  address: "https://vault.playteam.ru:8200/"
  authMethod: kubernetes
  kubernetesPath: auth/k8s-cluster1-prod-sbc
  kubernetesRole: vault-secrets-operator
  reconciliationTime: 3600

rbac:
  create: true
  createrole: true
  namespaced: false

serviceAccount:
  create: true
  name: vault-secrets-operator

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}


serviceMonitor:
  enabled: true
  labels:
    monitor: "true"
  interval: 30s
  scrapeTimeout: 10s
  honorLabels: true
  relabelings: []
