syncWave: "-20"
hookDeletePolicy: HookSucceeded,HookFailed

namespace: ""
serviceAccountName: argocd-manager
serviceAccountNamespace: kube-system
roleName: ""

rules: []
clusterRules: []

markerRole:
  enabled: true
  rules: []

image: registry.playteam.ru/bitnami/kubectl:1.24.14-debian-11-r3
