syncWave: "-1"
hookDeletePolicy: HookSucceeded,HookFailed

namespace: ""
serviceAccountName: argocd-manager
serviceAccountNamespace: kube-system
roleName: ""

rules: []

markerRole:
  enabled: true
  rules: []

image: bitnami/kubectl:latest
