apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Release.Name }}
    tier: node
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
      tier: node
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: {{ .Release.Name }}
        tier: node
    spec:
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: ''
        - name: ssl-certs-host
          hostPath:
            path: /etc/ssl/certs
            type: ''
        - name: kubeconfig
          configMap:
            name: kubeconfig-in-cluster
            defaultMode: 420
      initContainers:
        - name: init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /usr/local/bin/kube-proxy
            - '--cluster-cidr=$(CLUSTER_CIDR)'
            - '--conntrack-max-per-core=0'
            - '--hostname-override=$(NODE_NAME)'
            - '--kubeconfig=/etc/kubernetes/kubeconfig'
            - '--metrics-bind-address=$(METRICS_BIND_ADDRESS)'
            - '--proxy-mode=$(PROXY_MODE)'
            - '--init-only'
          env:
            - name: CLUSTER_CIDR
              value: {{ .Values.kubeProxy.clusterCidr }}
            - name: METRICS_BIND_ADDRESS
              value: {{ .Values.kubeProxy.metricsBindAddress }}
            - name: PROXY_MODE
              value: {{ .Values.kubeProxy.proxyMode }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 12 }}
{{- else }}
            {}
{{- end }}
          volumeMounts:
            - name: lib-modules
              readOnly: true
              mountPath: /lib/modules
            - name: ssl-certs-host
              readOnly: true
              mountPath: /etc/ssl/certs
            - name: kubeconfig
              readOnly: true
              mountPath: /etc/kubernetes
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
      containers:
        - name: kube-proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /usr/local/bin/kube-proxy
            - '--cluster-cidr=$(CLUSTER_CIDR)'
            - '--conntrack-max-per-core=0'
            - '--hostname-override=$(NODE_NAME)'
            - '--kubeconfig=/etc/kubernetes/kubeconfig'
            - '--metrics-bind-address=$(METRICS_BIND_ADDRESS)'
            - '--proxy-mode=$(PROXY_MODE)'
          env:
            - name: CLUSTER_CIDR
              value: {{ .Values.kubeProxy.clusterCidr }}
            - name: METRICS_BIND_ADDRESS
              value: {{ .Values.kubeProxy.metricsBindAddress }}
            - name: PROXY_MODE
              value: {{ .Values.kubeProxy.proxyMode }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 12 }}
{{- else }}
            {}
{{- end }}
          volumeMounts:
            - name: lib-modules
              readOnly: true
              mountPath: /lib/modules
            - name: ssl-certs-host
              readOnly: true
              mountPath: /etc/ssl/certs
            - name: kubeconfig
              readOnly: true
              mountPath: /etc/kubernetes
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: kube-proxy
      serviceAccount: kube-proxy
      hostNetwork: true
      securityContext: {}
      schedulerName: default-scheduler
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- else }}
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      priorityClassName: system-cluster-critical