---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
spec:
  sources:
  - secret:
      name: "{{ .Values.tokenSecretName }}"
      key: "tls.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
