
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: linkerd-proxy
  namespace: {{ .Release.Namespace }}
spec:
  podMetricsEndpoints:
    - port: linkerd-admin
      scheme:
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      linkerd.io/control-plane-ns: {{.Release.Namespace}}
