apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: {{ include "ztunnel.release-name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podMetricsEndpoints:
    - port: ztunnel-stats
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: ztunnel
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
