{{- if .Values.restrictLinkerdIdentityIssuer }}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-linkerd-identity-issuer
spec:
  background: false
  validationFailureAction: {{ .Values.restrictLinkerdIdentityIssuer.validationFailureAction }}
  rules:
    - name: block-secret-writes
      match:
        resources:
          kinds:
            - Secret
          namespaces:
            - linkerd
          names:
            - linkerd-identity-issuer
          operations:
            - CREATE
            - UPDATE
            - DELETE
      exclude:
        subjects:
          - kind: ServiceAccount
            name: linkerd-controller
            namespace: linkerd
          - kind: ServiceAccount
            name: linkerd-proxy
            namespace: linkerd
          - kind: ServiceAccount
            name: trust-manager
            namespace: kube-system
          - kind: ServiceAccount
            name: cert-manager
            namespace: kube-system
      validate:
        message: "Only specific service accounts are allowed to access linkerd-identity-issuer secret."
        deny: {}
{{- end }}