{{- if .Values.prometheusServiceMonitor.create }}
{{- if .Capabilities.APIVersions.Has "operator.victoriametrics.com/v1beta1/VMServiceScrape" }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "x509-certificate-exporter.fullname" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheusServiceMonitor.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
      scrapeTimeout: {{ .Values.prometheusServiceMonitor.scrapeTimeout }}
      {{- with .Values.prometheusServiceMonitor.relabelings }}
      relabelConfigs:
        {{- . | toYaml | nindent 4 }}
      {{- end }}
      {{- if .Values.rbacProxy.enable }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
  selector:
    matchLabels:
      {{- include "x509-certificate-exporter.selectorLabels" . | nindent 6 }}
{{- else }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "x509-certificate-exporter.fullname" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheusServiceMonitor.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "x509-certificate-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
    scrapeTimeout: {{ .Values.prometheusServiceMonitor.scrapeTimeout }}
    {{- if .Values.rbacProxy.enable }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    {{- end }}
    {{- with .Values.prometheusServiceMonitor.relabelings }}
    relabelings:
    {{- . | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
