---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.username }}
  labels:
    app: {{ .Values.username }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.username }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.username }}
  apiGroup: rbac.authorization.k8s.io