---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: talos-vmtoolsd-config
  namespace: {{ .Values.namespace }}
spec:
  path: {{ .Values.vault.path }}
  type: {{ .Values.vault.type }}